### ISSUE TITLE
WhatsChrome doesn't play well?

### ISSUE THREAD

**Issue by ckdarby** [danbruce/i3-tracker-rs#5]
Expected:
WhatsChrome, Google-Chrome

Got:
WhatsChrome,crx_bgkodfmeijboinjdegggmkbkjfiagaan

```text
1051,54525978,WhatsChrome,crx_bgkodfmeijboinjdegggmkbkjfiagaan,2018-03-20 10:24:16,2018-03-20 10:24:17,1
```

**Comment by danbruce** [comment]
WONTFIX

To be fair, this is something that should be cleaned up by a tool down the road. Maybe I'll write one.

But honestly, it's just the app title coming back from Xorg/i3 and there's nothing time-tracker can do really. It's not in the scope of the project to fix this, only to capture it.
